services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $rootDir: '%kernel.project_dir%'
            $translationPath: '%translator.default_path%'

    cavern_bay.translation.command.export:
        class: CavernBay\TranslationBundle\Command\ExportCommand

    cavern_bay.translation.command.import:
        class: CavernBay\TranslationBundle\Command\ImportCommand
