services:
    cavern_bay.translation.command.export:
        class: CavernBay\TranslationBundle\Command\ExportCommand

    cavern_bay.translation.command.import:
        class: CavernBay\TranslationBundle\Command\ImportCommand
